-- ============================================================================
--  Flesh and Blood collection tracker — card pricing add-on
--  Paste this into the Supabase SQL editor and run it once, after
--  supabase.sql. Re-runnable.
--
--  What this adds:
--    card_printing      -- card_id -> TCGPlayer product id(s). Seed from
--                           tcgplayer_map.csv (tools/build_cards.py now
--                           writes this alongside cards.json/cards.csv).
--    card_price         -- one row per (product, day): market/low/mid/high.
--    price_sync_log     -- one row per sync_fab_prices() run: what it walked,
--                           what failed, and why -- so "did last night's sync
--                           actually work" is a query, not a guess.
--    sync_fab_prices()  -- pulls today's prices from TCGCSV and upserts them.
--    get_card_values()  -- public RPC: cheapest current price per card_id.
--
--  Design notes:
--   - The tracker counts unique cards (name + pitch), but TCGPlayer prices
--     are per *printing*. get_card_values() reports the cheapest printing's
--     EFFECTIVE price per card -- market price if TCGPlayer has computed
--     one, else mid, else low, in that order -- along with which tier it
--     used and the full low/mid/high, so the app can show a real fallback
--     estimate without pretending it's an actual traded price.
--   - card_price keeps one row per day rather than just "latest", so a
--     future "alert me when a card dips" feature needs no schema change --
--     just read history for a card_id's mapped product ids.
--   - Pricing is public market data, not per-user data, so get_card_values()
--     needs no collection code, unlike get_collection/set_qty/set_many.
--   - sync_fab_prices() treats each of the ~100+ TCGCSV groups (sets) as its
--     own sub-transaction: one bad HTTP call only costs that group's prices
--     for the night, not the whole run.
-- ============================================================================

create extension if not exists http with schema extensions;
create extension if not exists pg_cron;   -- pg_cron pins itself to schema "cron"

-- ---------------------------------------------------------------- reference
-- Seed / refresh from tcgplayer_map.csv: Table editor -> card_printing ->
-- Import data from CSV. A card can have several rows if it has multiple
-- printings sold as separate TCGPlayer products; a card with no row here
-- simply shows no price in the app (mostly obscure con-exclusive promos).
--
-- Primary key is the PAIR, not tcgplayer_id alone: a small number of
-- TCGPlayer product ids are shared by more than one card (mostly generic
-- Token listings that bundle a few different tokens under one product), so
-- tcgplayer_id on its own isn't unique.
create table if not exists public.card_printing (
  tcgplayer_id bigint not null,
  card_id      text   not null,
  primary key (card_id, tcgplayer_id)
);
create index if not exists card_printing_card_idx      on public.card_printing (card_id);
create index if not exists card_printing_tcgplayer_idx  on public.card_printing (tcgplayer_id);

-- Already created this table with tcgplayer_id alone as the primary key
-- (an earlier version of this file did)? This widens it without you having
-- to recreate the table. Safe to run more than once.
truncate table public.card_printing;
alter table public.card_printing drop constraint if exists card_printing_pkey;
alter table public.card_printing add  constraint card_printing_pkey
  primary key (card_id, tcgplayer_id);

-- One row per product per day, upserted daily by sync_fab_prices(). If a
-- product has more than one price row for the day (distinct sub-types), the
-- cheapest EFFECTIVE price (market, else mid, else low) wins -- see the on
-- conflict guard below.
create table if not exists public.card_price (
  tcgplayer_id  bigint not null,
  price_date    date   not null,
  market_price  numeric(10,2),
  low_price     numeric(10,2),
  mid_price     numeric(10,2),
  high_price    numeric(10,2),
  primary key (tcgplayer_id, price_date)
);
create index if not exists card_price_date_idx on public.card_price (price_date);

-- One row per sync_fab_prices() run.
create table if not exists public.price_sync_log (
  id              bigint generated by default as identity primary key,
  run_at          timestamptz not null default now(),
  groups_walked   int,
  groups_failed   int,
  rows_considered int,
  rows_stored     int,
  errors          jsonb          -- [{"group_id": "...", "message": "..."}]
);

-- ------------------------------------------------------------------- lockdown
-- Same model as collection/collection_card: RLS on, no policies, so anon
-- gets nothing directly. sync_fab_prices() and get_card_values() are
-- security definer, so they can still read and write through the lockdown.
alter table public.card_printing enable row level security;
alter table public.card_price    enable row level security;
alter table public.price_sync_log enable row level security;
revoke all on public.card_printing from anon, authenticated;
revoke all on public.card_price    from anon, authenticated;
revoke all on public.price_sync_log from anon, authenticated;

-- ------------------------------------------------------------------ functions

-- Walks every Flesh & Blood group (set, category 62) on TCGCSV and stores
-- today's prices for any product id mapped in card_printing. Everything
-- else on TCGCSV (sealed product, playmats, other games) is never mapped,
-- so it's implicitly ignored.
--
-- Each group runs inside its own begin/exception block, so one bad request
-- (timeout, malformed response) only skips that group -- every other group
-- still commits, and the failure is recorded in price_sync_log instead of
-- rolling back the whole run.
--
-- Test it by hand before trusting the schedule below:
--   select * from public.sync_fab_prices();
--   select * from public.price_sync_log order by run_at desc limit 5;
drop function if exists public.sync_fab_prices();
create function public.sync_fab_prices()
returns table (groups_walked int, groups_failed int, rows_considered int, rows_stored int)
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_groups          jsonb;
  v_group           jsonb;
  v_group_id        text;
  v_prices          jsonb;
  v_row             jsonb;
  v_today           date := current_date;
  v_groups_walked   int := 0;
  v_groups_failed   int := 0;
  v_rows_considered int := 0;
  v_rows_stored     int := 0;
  v_product_id      bigint;
  v_market          numeric;
  v_errors          jsonb := '[]'::jsonb;
begin
  select (content::jsonb -> 'results') into v_groups
  from http_get('https://tcgcsv.com/tcgplayer/62/groups');

  for v_group in select * from jsonb_array_elements(coalesce(v_groups, '[]'::jsonb))
  loop
    v_group_id := v_group->>'groupId';
    begin
      v_groups_walked := v_groups_walked + 1;

      select (content::jsonb -> 'results') into v_prices
      from http_get(format('https://tcgcsv.com/tcgplayer/62/%s/prices', v_group_id));

      for v_row in select * from jsonb_array_elements(coalesce(v_prices, '[]'::jsonb))
      loop
        v_rows_considered := v_rows_considered + 1;
        v_product_id := nullif(v_row->>'productId', '')::bigint;
        v_market     := nullif(v_row->>'marketPrice', '')::numeric;

        if v_product_id is not null
           and exists (select 1 from card_printing cp where cp.tcgplayer_id = v_product_id)
        then
          insert into card_price (tcgplayer_id, price_date, market_price, low_price, mid_price, high_price)
          values (
            v_product_id, v_today, v_market,
            nullif(v_row->>'lowPrice', '')::numeric,
            nullif(v_row->>'midPrice', '')::numeric,
            nullif(v_row->>'highPrice', '')::numeric
          )
          on conflict (tcgplayer_id, price_date) do update
            set market_price = excluded.market_price,
                low_price    = excluded.low_price,
                mid_price    = excluded.mid_price,
                high_price   = excluded.high_price
            where coalesce(card_price.market_price, card_price.mid_price, card_price.low_price) is null
               or coalesce(excluded.market_price, excluded.mid_price, excluded.low_price)
                  < coalesce(card_price.market_price, card_price.mid_price, card_price.low_price);

          v_rows_stored := v_rows_stored + 1;
        end if;
      end loop;
    exception when others then
      v_groups_failed := v_groups_failed + 1;
      v_errors := v_errors || jsonb_build_object('group_id', v_group_id, 'message', sqlerrm);
    end;
  end loop;

  insert into public.price_sync_log (groups_walked, groups_failed, rows_considered, rows_stored, errors)
  values (v_groups_walked, v_groups_failed, v_rows_considered, v_rows_stored, v_errors);

  return query select v_groups_walked, v_groups_failed, v_rows_considered, v_rows_stored;
end $$;

-- TCGCSV refreshes daily around 20:00 UTC; 21:00 UTC leaves a margin.
-- The where-not-exists guard makes this block safe to run again later.
select cron.schedule('sync-fab-prices-daily', '0 21 * * *', $$select public.sync_fab_prices();$$)
where not exists (select 1 from cron.job where jobname = 'sync-fab-prices-daily');

-- Cheapest current printing per card, by EFFECTIVE price (market, else mid,
-- else low). Joins to the latest price_date on file per product
-- individually, so one group mid-sync doesn't blank out prices for cards in
-- groups that already finished. Reports which tier won plus the full
-- low/mid/high for that printing, so a mid/low fallback can be shown
-- honestly rather than looking like a real market price.
drop function if exists public.get_card_values();
create function public.get_card_values()
returns table (
  card_id text, value numeric, tier text,
  low_price numeric, mid_price numeric, high_price numeric,
  price_date date, priced_printings int
)
language plpgsql stable security definer set search_path = public as $$
begin
  return query
    select distinct on (cp.card_id)
      cp.card_id,
      latest.effective_price,
      latest.tier,
      latest.low_price, latest.mid_price, latest.high_price,
      latest.price_date,
      (count(*) over (partition by cp.card_id))::int as priced_printings
    from card_printing cp
    join lateral (
      select p.price_date, p.low_price, p.mid_price, p.high_price,
             coalesce(p.market_price, p.mid_price, p.low_price) as effective_price,
             case when p.market_price is not null then 'market'
                  when p.mid_price    is not null then 'mid'
                  when p.low_price    is not null then 'low'
             end as tier
      from card_price p
      where p.tcgplayer_id = cp.tcgplayer_id
      order by p.price_date desc
      limit 1
    ) latest on true
    where latest.effective_price is not null
    order by cp.card_id, latest.effective_price asc;
end $$;

-- ------------------------------------------------------------------- grants
grant execute on function public.get_card_values() to anon, authenticated;
